using EventHub.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace EventHub.Infrastructure.Persistence.Configurations;

internal sealed class OutboxMessageConfiguration : IEntityTypeConfiguration<OutboxMessage>
{
    public void Configure(EntityTypeBuilder<OutboxMessage> builder)
    {
        builder.ToTable("OutboxMessages");

        builder.HasKey(m => m.Id);

        // Id is always assigned by OutboxMessage.Create() — never generated by the database.
        // Explicitly declaring this prevents EF Core from emitting OUTPUT INSERTED.Id in
        // INSERT batches, which avoids result-set misalignment causing DbUpdateConcurrencyException.
        builder.Property(m => m.Id).ValueGeneratedNever();

        builder.Property(m => m.Type)
            .IsRequired()
            .HasMaxLength(200);

        builder.Property(m => m.Payload)
            .IsRequired();

        builder.Property(m => m.CreatedAt).IsRequired();

        // Index to efficiently poll for unpublished messages
        builder.HasIndex(m => m.PublishedAt);
    }
}
