@host = https://eventhub-dev-api.azurewebsites.net
@bearerToken = <PASTE_USER_JWTS_TOKEN>


# Health check
GET {{host}}/healthz

###
# Get my events (Organizer/Admin)
GET {{host}}/api/events
Authorization: Bearer {{bearerToken}}
Accept: application/json


